FROM openjdk:17-alpine
COPY ./target/*-standalone.jar /home/beholder-standalone.jar
ENTRYPOINT java \
-Des-hosts=http://host.minikube.internal:9200 \
-Dk8s-apiserver=https://kubernetes.default.svc \
-Dk8s-token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) \
-server \
-jar /home/beholder-standalone.jar